# Generated by Django 4.1.5 on 2023-01-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='img',
            field=models.ImageField(default='jyggg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
